# Default values for bitwarden-rs.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

# replicaCount -- Number of pods to run. >1 has NOT been tested
replicaCount: 1

image:

  # image.repository -- Docker registry/repository to pull the image from
  repository: vaultwarden/server

  # image.tag -- Overrides the image tag used
  tag:

  # image.pullPolicy -- Docker image pull policy
  pullPolicy: IfNotPresent

  # image.pullSecrets -- Secrets to use when pulling Docker images
  pullSecrets: []

# nameOverride -- Overrides the name of resources
nameOverride: ""

# fullnameOverride -- Overrides the Full Name of resources
fullnameOverride: ""

credentials:

  # credentials.useExistingSecret -- Set this to true to use your own Secret, created outside of this deployment. Expects `adminToken`, `mysql-password`, and `mysql-root-password`.
  useExistingSecret: false

  # credentials.secretName -- name of the secret which contains Bitwarden Admin token and DB Password. NOTE: if you change this you must also change mysql.existingSecret to match.
  secretName: bitwarden

  # credentials.yubicoSecretKey -- Key used in `credentials.secretName` that contains your Yubico Secret Key. [Docs](https://github.com/dani-garcia/bitwarden_rs/wiki/Enabling-Yubikey-OTP-authentication)
  yubicoSecretKey: ""

bitwardenConfig:

  ## Bitwarden Configuration ##
  #   This section allows for the setting of configuration
  #   options by setting environment variables. Any Key in
  #   in this section will be uppercased and set as an env
  #   var with its respective vale.

  # bitwardenConfig.domain -- (Optioinal) Override the domain used by Bitwarden. By default it uses the first host defined in your Ingress if defined, otherwise the "fullname" of the service.
  # domain: bw.domain.tld

  # bitwardenConfig.signups_allowed -- (Optional) By default new users can register. Set to false to disable signups. [Docs](https://github.com/dani-garcia/bitwarden_rs/wiki/Disable-registration-of-new-users)
  # signups_allowed: true

  # bitwardenConfig.invitations_allowed -- (Optional) set to false to prevent standard users from inviting others. [Docs](https://github.com/dani-garcia/bitwarden_rs/wiki/Disable-invitations)
  # invitations_allowed: true

  # bitwardenConfig.rocket_tls -- (Optional) Enables SSL/TLS on the Web Service, securing traffic between it and the ingreess. [Docs](https://github.com/dani-garcia/bitwarden_rs/wiki/Enabling-HTTPS)
  # rocket_tls: "{certs=\"/ssl/certs.pem\",key=\"/ssl/key.pem\"}"

  # bitwardenConfig.data_folder -- parent directory for all Bitwarden persisted data. [Docs](https://github.com/dani-garcia/bitwarden_rs/wiki/Changing-persistent-data-location#data-prefix)
  data_folder: "/data"

  # bitwardenConfig.attachments_folder -- (Optional) set the directory for attachments. Defaults to `$DATA_FOLDER/attachments`. [Docs](https://github.com/dani-garcia/bitwarden_rs/wiki/Changing-persistent-data-location#attachments-location)
  # attachments_folder: $DATA_FOLDER/attachments

  # bitwardenConfig.icon_cache_folder -- (Optional) set the directory icon cache (ie. favicon). Defaults to `$DATA_FOLDER/icon_cache`. [Docs](https://github.com/dani-garcia/bitwarden_rs/wiki/Changing-persistent-data-location#icons-cache)
  # icon_cache_folder: $DATA_FOLDER/icon_cache

  # bitwardenConfig.rocket_limits -- (Optional) API request size limits. [Docs](https://github.com/dani-garcia/bitwarden_rs/wiki/Changing-the-API-request-size-limit)
  # rocket_limits: "{json=10485760}"

  # bitwardenConfig.rocket_workers -- (Optional) Number of worker threads to handle requests. [Docs](https://github.com/dani-garcia/bitwarden_rs/wiki/Changing-the-number-of-workers)
  # rocket_workers: 10

  # bitwardenConfig.yubicoClientId -- (Optional) Client ID for your YubiKey. Must also set `credentials.yubicoSecretKey`. [Docs](https://github.com/dani-garcia/bitwarden_rs/wiki/Enabling-Yubikey-OTP-authentication)
  # yubico_client_id:

  # bitwardenConfig.yubicoServer -- (Optional) Override the YubiCo server. Defaults to YubiCloud servers. [Docs](https://github.com/dani-garcia/bitwarden_rs/wiki/Enabling-Yubikey-OTP-authentication)
  # yubico_server:

  ## SMTP Configuration ##
  # Setup SMTP to enable notifications and invitations

  # bitwardenConfig.smtp_host -- (Optional) SMTP server address. [Docs](https://github.com/dani-garcia/bitwarden_rs/wiki/SMTP-configuration)
  # smtp_host: smtp.domain.tld

  # bitwardenConfig.port -- (Optional) SMTP server port. [Docs](https://github.com/dani-garcia/bitwarden_rs/wiki/SMTP-configuration)
  # smtp_port: 587

  # bitwardenConfig.smtp_from -- (Optional) From email address for Bitwarden. [Docs](https://github.com/dani-garcia/bitwarden_rs/wiki/SMTP-configuration)
  # smtp_from: bitwarden@domain.tld

  # bitwardenConfig.smtp_ssl -- (Optional) Enable/Disable SSL. Defaults to `true`. [Docs](https://github.com/dani-garcia/bitwarden_rs/wiki/SMTP-configuration)
  # smtp_ssl: true

  # bitwardenConfig.smtp_username -- (Optional) Username to use when authenticating to the SMTP server. [Docs](https://github.com/dani-garcia/bitwarden_rs/wiki/SMTP-configuration)
  # smtp_username: username

  # bitwardenConfig.smtp_password -- (Optional) Password to use when authenticating to the SMTP server. [Docs](https://github.com/dani-garcia/bitwarden_rs/wiki/SMTP-configuration)
  # smtp_password: password

  # bitwardenConfig.show_password_hints -- Enables the display of Password Hints instead of sending via email. It is recommended to leave this disabled. [Docs](https://github.com/dani-garcia/bitwarden_rs/wiki/Password-hint-display)
  show_password_hints: false

  # bitwardenConfig.web_vault_enabled -- Enables the Web Valut (UI) interface. [Docs](https://github.com/dani-garcia/bitwarden_rs/wiki/Disabling-or-overriding-the-Vault-interface-hosting)
  web_vault_enabled: true

  # bitwardenConfig.log_file -- (Optional) File location to send logs to. [Docs](https://github.com/dani-garcia/bitwarden_rs/wiki/Logging)
  # log_file: "/data/bitwarden.log"

  # bitwardenConfig.log_level -- Sets the LOG_LEVEL. [Docs](https://github.com/dani-garcia/bitwarden_rs/wiki/Logging#change-the-log-level)
  log_level: "info"

  # bitwardenConfig.websocket_enabled -- Enables Web Browser notifications through the use of WebSockets. [Docs](https://github.com/dani-garcia/bitwarden_rs/wiki/Enabling-WebSocket-notifications)
  # TODO: Either setup complicated Ingress routing or wait for [in-built support](https://github.com/SergioBenitez/Rocket/issues/90)
  # websocket_enabled = false

serviceAccount:
  
  # serviceAccount.create -- Specifies whether a service account should be created
  create: true

  # serviceAccount.name -- (string) name of the service account to use. If not set and create is true, a name is generated using the fullname template
  # name:

## Persist data to a persistent volume
persistence:

  # persistence.enabled -- Enables persistence of the Bitwarden_rs `/data` directory
  enabled: false
  
  ## Bitwarden data Persistent Volume Storage Class
  ## If defined, storageClassName: <storageClass>
  ## If set to "-", storageClassName: "", which disables dynamic provisioning
  ## If undefined (the default) or set to null, no storageClassName spec is
  ##   set, choosing the default provisioner.  (gp2 on AWS, standard on
  ##   GKE, AWS & OpenStack)
  
  # persistence.storageClass -- (Optional) StorageClass to use for the PVC
  # storageClass: "-"
  
  # persistence.accessMode -- [access mode](https://kubernetes.io/docs/concepts/storage/persistent-volumes/#access-modes) to use for the PVC
  accessMode: ReadWriteOnce
  
  # persistence.size -- size/capacity of the PVC
  size: 8Gi

  # persistence.annotations -- (Optional) annotations to add to the PVC
  annotations: {}

service:
  type: ClusterIP
  port: 80

ingress:

  # ingress.enabled -- Enables the use of an Ingress Controller to front the Service and provide HTTPS
  enabled: false
  
  # ingress.annotations -- annotations to configure your Ingress. See your Ingress Controller's Docs for more info.
  annotations: {}
    # kubernetes.io/ingress.class: nginx
    # kubernetes.io/tls-acme: "true"
  
  # ingress.hosts -- list of hosts and their paths that ingress controller should repsond to. First host will be used to set the Bitwarden `DOMAIN`.
  hosts:
    - host: chart-example.local
      paths:
        - '/'
  
  # ingress.tls -- list of TLS configurations
  tls: []
  #  - secretName: chart-example-tls
  #    hosts:
  #      - chart-example.local

# resources -- Set resource limits/requests for the Pod(s)
resources: {}
  # limits:
  #   cpu: 100m
  #   memory: 128Mi
  # requests:
  #   cpu: 100m
  #   memory: 128Mi

# nodeSelector -- Node Selector configuration
nodeSelector: {}

# tolerations -- Node toleration configuration
tolerations: []

# affinity -- Set Pod affinity rules
affinity: {}

# podSecurityContext -- Set Pod security contexts
podSecurityContext: {}
  # fsGroup: 2000

# securityContext -- Set Security Context
securityContext: {}
  # capabilities:
  #   drop:
  #   - ALL
  # readOnlyRootFilesystem: true
  # runAsNonRoot: true
  # runAsUser: 1000

# mysql -- MySQL HelmChart configuration options. See [docs](https://github.com/helm/charts/tree/master/stable/mysql)
mysql:

  # mysql.enabled -- Set to `false` to skip MySQL deployment and use and external instance. Must also set `mysql.externalHost`.
  enabled: true

  # mysql.existingSecret -- Secret to reference for MySQL credentials
  existingSecret: bitwarden

  # mysql.mysqlDatabase -- Database name for Bitwarden
  mysqlDatabase: bitwarden

  # mysql.mysqlUser -- Username Bitwarden should use
  mysqlUser: bitwarden

  service:

    # mysql.service.port -- Port MySQL should use for connections
    port: 3306

  # mysql.externalHost -- Sets an external host to use instead of the included MySQL chart dependency. Must also set `mysql.enabled: false`.
  externalHost: