apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "navidrome.fullname" . }}-config
  labels:
    {{- include "navidrome.labels" . | nindent 4 }}
data: 
  navidrome.yml: |-
    {{ .Values.config | toYaml | nindent 4 }}
