apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: {{ include "intel-gpu.fullname" . }}
  labels:
    {{- include "intel-gpu.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      {{- include "intel-gpu.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "intel-gpu.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "intel-gpu.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      initContainers:
        - name: intel-gpu-initcontainer
          image: "{{ .Values.initContainerImage.repository }}:{{ .Values.initContainerImage.tag | default .Chart.AppVersion }}"
          imagePullPolicy: IfNotPresent
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          volumeMounts:
            # TODO
            - mountPath: /etc/kubernetes/node-feature-discovery/source.d/
              name: nfd-source-hooks
      containers:
        - name: intel-gpu-plugin
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
          # TODO:
          # livenessProbe:
          #   httpGet:
          #     path: /
          #     port: http
          # readinessProbe:
          #   httpGet:
          #     path: /
          #     port: http
          volumeMounts:
            - name: devfs
              mountPath: /dev/dri
              readOnly: true
            - name: sysfs
              mountPath: /sys/class/drm
              readOnly: true
            - name: kubeletsockets
              mountPath: /var/lib/kubelet/device-plugins
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      volumes:
        - name: devfs
          hostPath:
            path: /dev/dri
        - name: sysfs
          hostPath:
            path: /sys/class/drm
        - name: kubeletsockets
          hostPath:
            path: /var/lib/kubelet/device-plugins
        # TODO: Is this needed if NFD is NOT installed?
        - name: nfd-source-hooks
          hostPath:
            path: /etc/kubernetes/node-feature-discovery/source.d/
            type: DirectoryOrCreate
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
